###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: "3.1"
services:

    mysql:
      image: mysql:8.0
      working_dir: /application
      volumes:
        - ./source:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=qdoctor
        - MYSQL_USER=qdoctor
        - MYSQL_PASSWORD=secret
      ports:
        - "10002:3306"

    webserver:
      image: nginx:alpine
      working_dir: /application
      volumes:
          - ./source:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "10000:80"

    php-fpm:
      build: phpdocker/php-fpm
      working_dir: /application
      volumes:
        - ./source:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini

